# Generated by Django 2.2.2 on 2019-06-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190617_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.BooleanField(null=True),
        ),
    ]
