# Generated by Django 2.2.2 on 2019-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.NullBooleanField(),
        ),
    ]
