# Generated by Django 2.2.2 on 2019-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20190617_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.BooleanField(null=True),
        ),
    ]
