# Generated by Django 2.2.2 on 2019-07-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20190617_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
